### ISSUE TITLE
macOS app download is blocked by Chrome as suspicous

### ISSUE THREAD

**Issue by jt-wang** [Helixform/GetFileTunnel#3]
![CleanShot 2024-04-24 at 19 50 28@2x](https://github.com/Helixform/GetFileTunnel/assets/7776499/2ca44e09-1358-4c7e-a1bc-ca46f60398fa)

**Comment by unixzii** [comment]
We are still investigating it. You can click "Download suspicious file" button to download it before the issue is resolved.

<img width="699" alt="image" src="https://github.com/Helixform/GetFileTunnel/assets/3109144/f0469bd5-ef1d-4621-b636-2eb45621e77d">
